EDITORCONFIG_CHECKER ?= $(call which,EDITORCONFIG_CHECKER,editorconfig-checker)
$(call make-lazy,EDITORCONFIG_CHECKER)

# NOTE add more patterns with |
EDITORCONFIG_CHECKER_EXCLUDE ?= ^$$

EDITORCONFIG_CHECKER_FLAGS += \
	-no-color \

EDITORCONFIG_CHECKER_FILES += \
	$(EDITORCONFIG_CHECKER_FILES_EXT) \

EDITORCONFIG_CHECKER_FILES_EXT = $(shell $(GIT_LS) | $(NOSYM))

EDITORCONFIG_CHECKER_FILES_FILTER_OUT += \
	$(DEFAULT_FILES_FILTER_OUT) \

# ------------------------------------------------------------------------------

.PHONY: debug/editorconfig-checker
debug/editorconfig-checker:
	$(ECHO)
	$(ECHO_DO) "Debug EditorConfig Checker..."
	$(ECHO) "EDITORCONFIG_CHECKER=$(EDITORCONFIG_CHECKER)"
	$(ECHO) "EDITORCONFIG_CHECKER_EXCLUDE=$(EDITORCONFIG_CHECKER_EXCLUDE)"
	$(ECHO) "EDITORCONFIG_CHECKER_FILES=$(EDITORCONFIG_CHECKER_FILES)"
	$(ECHO) "EDITORCONFIG_CHECKER_FILES_EXT=$(EDITORCONFIG_CHECKER_FILES_EXT)"
	$(ECHO) "EDITORCONFIG_CHECKER_FILES_FILTER_OUT=$(EDITORCONFIG_CHECKER_FILES_FILTER_OUT)"
	$(ECHO) "EDITORCONFIG_CHECKER_FLAGS=$(EDITORCONFIG_CHECKER_FLAGS)"
	set -x && $(EDITORCONFIG_CHECKER) --version || true
	$(ECHO_DONE)


.PHONY: check/editorconfig-checker
check/editorconfig-checker:
	EDITORCONFIG_CHECKER_FILES_TMP=( \
		$(filter-out $(EDITORCONFIG_CHECKER_FILES_FILTER_OUT), $(EDITORCONFIG_CHECKER_FILES))); \
	[[ "$${#EDITORCONFIG_CHECKER_FILES_TMP[@]}" = "0" ]] || { \
		$(EDITORCONFIG_CHECKER) -exclude "$(EDITORCONFIG_CHECKER_EXCLUDE)" $(EDITORCONFIG_CHECKER_FLAGS) \
			$${EDITORCONFIG_CHECKER_FILES_TMP[@]} 2>&1 \
				| { $(GREP) -v -e "^0 errors found" || true; }; \
	}
