name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu24.04:latest
      options: --user linuxbrew
    steps:
      - uses: Homebrew/actions/setup-homebrew@main
      - uses: actions/checkout@v4
      - run: make system
      - run: make ci
