name: CI

'on':
  push: null
  pull_request: null

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu24.04:latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@main
      - uses: actions/checkout@v6
      - run: V=1 make system
      - run: V=1 make ci
